name: My Workflow

on:
  push:
    branches:
      - restructure

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, world!"
