CREATE DATABASE IF NOT EXISTS booksdb; 

USE booksdb; 

CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    subject_facet LONGTEXT NOT NULL
);
